USE master;

IF EXISTS(SELECT * FROM sys.databases WHERE name = 'db01')
BEGIN
	ALTER DATABASE db01 SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE db01;
END
GO
CREATE DATABASE db01;
GO

USE [master]
GO
ALTER DATABASE [db01] SET FILESTREAM( NON_TRANSACTED_ACCESS = FULL, DIRECTORY_NAME = N'dbDIR' ) WITH NO_WAIT
GO

GO
ALTER DATABASE [db01] ADD FILEGROUP [fs] CONTAINS FILESTREAM 
GO
ALTER DATABASE [db01] ADD FILE ( NAME = N'db01_fs', FILENAME = N'C:\SQLData\db01_fs' ) TO FILEGROUP [fs]
GO
USE db01;

CREATE TABLE dbo.FSTable AS FILETABLE
  WITH
  (
    FILETABLE_DIRECTORY = 'fsDIR',
    FILETABLE_COLLATE_FILENAME = database_default
  )

  SELECT * FROM dbo.FSTable

  SELECT * FROM dbo.FSTable
    WHERE stream_id = '122287B0-8B07-F011-9269-00155D0E2E0B';

  SELECT CAST(file_stream AS varchar(max)) FROM dbo.FSTable
    WHERE stream_id = '122287B0-8B07-F011-9269-00155D0E2E0B';

	DELETE FROM dbo.FSTable

BACKUP DATABASE db01 TO DISK='db01.bak'

RESTORE FILELISTONLY
FROM DISK='db01.bak'

USE master;

IF EXISTS(SELECT * FROM sys.databases WHERE name = 'db01')
BEGIN
	ALTER DATABASE db01 SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE db01;
END
GO

--Stop Filestream

RESTORE DATABASE db01
FROM DISK='db01.bak'

USE db01;

SELECT * FROM dbo.FSTable;


